# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kimoo\PycharmProjects\TrafficGenerator\traffic_generator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 457)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(480, 10, 231, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 10, 101, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label_17.setObjectName("label_17")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 190, 201, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 20, 70, 21))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 40, 70, 21))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_15.setGeometry(QtCore.QRect(10, 60, 70, 21))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_16.setGeometry(QtCore.QRect(100, 60, 70, 21))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_17.setGeometry(QtCore.QRect(100, 40, 70, 21))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_18.setGeometry(QtCore.QRect(100, 20, 70, 21))
        self.checkBox_18.setObjectName("checkBox_18")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_13.setGeometry(QtCore.QRect(110, 40, 101, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_18.setObjectName("label_18")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_14.setGeometry(QtCore.QRect(110, 70, 101, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.label_19.setObjectName("label_19")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_15.setGeometry(QtCore.QRect(110, 100, 101, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_20.setObjectName("label_20")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_16.setGeometry(QtCore.QRect(110, 130, 101, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(10, 130, 61, 21))
        self.label_21.setObjectName("label_21")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_17.setGeometry(QtCore.QRect(110, 160, 101, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 61, 21))
        self.label_22.setObjectName("label_22")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_18.setGeometry(QtCore.QRect(110, 290, 101, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(10, 290, 61, 21))
        self.label_23.setObjectName("label_23")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_19.setGeometry(QtCore.QRect(110, 320, 101, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(10, 320, 61, 21))
        self.label_24.setObjectName("label_24")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_20.setGeometry(QtCore.QRect(130, 350, 81, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(10, 350, 61, 21))
        self.label_25.setObjectName("label_25")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_19.setGeometry(QtCore.QRect(70, 350, 70, 21))
        self.checkBox_19.setObjectName("checkBox_19")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(110, 10, 101, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label_26.setObjectName("label_26")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(110, 40, 101, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_28.setObjectName("label_28")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(130, 70, 81, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_20.setGeometry(QtCore.QRect(70, 70, 70, 21))
        self.checkBox_20.setObjectName("checkBox_20")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.label_29.setObjectName("label_29")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_24.setGeometry(QtCore.QRect(130, 100, 81, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_21.setGeometry(QtCore.QRect(70, 100, 70, 21))
        self.checkBox_21.setObjectName("checkBox_21")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_38.setGeometry(QtCore.QRect(130, 130, 81, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.checkBox_31 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_31.setGeometry(QtCore.QRect(70, 130, 70, 21))
        self.checkBox_31.setObjectName("checkBox_31")
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setGeometry(QtCore.QRect(10, 130, 61, 21))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label_44.setObjectName("label_44")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_40.setGeometry(QtCore.QRect(110, 40, 101, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        self.label_45.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_45.setObjectName("label_45")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_41.setGeometry(QtCore.QRect(110, 70, 101, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        self.label_46.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_46.setObjectName("label_46")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_42.setGeometry(QtCore.QRect(110, 100, 101, 20))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.label_47.setObjectName("label_47")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_4.setGeometry(QtCore.QRect(110, 10, 101, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 451, 21))
        self.comboBox.setObjectName("comboBox")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 59, 451, 371))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 151, 151))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 70, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 70, 70, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 90, 70, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 120, 61, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 180, 251, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 231, 121))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 140, 101, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_7.setGeometry(QtCore.QRect(120, 20, 70, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_8.setGeometry(QtCore.QRect(120, 80, 70, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_9.setGeometry(QtCore.QRect(120, 140, 70, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 20, 111, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(200, 0, 111, 20))
        self.label_10.setObjectName("label_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 80, 51, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(200, 60, 61, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(200, 120, 61, 20))
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 140, 51, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(260, 120, 61, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(260, 140, 51, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(380, 140, 51, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(380, 120, 61, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(320, 140, 51, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(320, 120, 61, 20))
        self.label_15.setObjectName("label_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 10, 101, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 20, 70, 21))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 40, 70, 21))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 60, 70, 21))
        self.checkBox_12.setObjectName("checkBox_12")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(260, 60, 61, 20))
        self.label_16.setObjectName("label_16")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(260, 80, 51, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 11, 111, 20))
        self.label.setObjectName("label")
        self.checkBox_32 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_32.setGeometry(QtCore.QRect(840, 30, 70, 17))
        self.checkBox_32.setObjectName("checkBox_32")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(730, 10, 61, 20))
        self.label_48.setObjectName("label_48")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_39.setGeometry(QtCore.QRect(730, 30, 101, 20))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.checkBox_33 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_33.setGeometry(QtCore.QRect(840, 70, 70, 17))
        self.checkBox_33.setObjectName("checkBox_33")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_43.setGeometry(QtCore.QRect(730, 70, 101, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(730, 50, 91, 20))
        self.label_49.setObjectName("label_49")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(730, 100, 181, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_7)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 161, 111))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 159, 109))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 181, 111))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(740, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 250, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(740, 280, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(830, 280, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(730, 310, 181, 51))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_44.setGeometry(QtCore.QRect(10, 20, 161, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(740, 370, 161, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(830, 400, 75, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(740, 400, 75, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traffic Generator"))
        self.label_17.setText(_translate("MainWindow", "Source Port"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Flags"))
        self.checkBox_13.setText(_translate("MainWindow", "URG"))
        self.checkBox_14.setText(_translate("MainWindow", "ACK"))
        self.checkBox_15.setText(_translate("MainWindow", "PSH"))
        self.checkBox_16.setText(_translate("MainWindow", "FIN"))
        self.checkBox_17.setText(_translate("MainWindow", "SYN"))
        self.checkBox_18.setText(_translate("MainWindow", "RST"))
        self.label_18.setText(_translate("MainWindow", "Destination Port"))
        self.label_19.setText(_translate("MainWindow", "Seq. number"))
        self.label_20.setText(_translate("MainWindow", "Ack. number"))
        self.label_21.setText(_translate("MainWindow", "Offset"))
        self.label_22.setText(_translate("MainWindow", "Reserved"))
        self.label_23.setText(_translate("MainWindow", "Wind. size"))
        self.label_24.setText(_translate("MainWindow", "Ur. pointer"))
        self.label_25.setText(_translate("MainWindow", "Checksum"))
        self.checkBox_19.setText(_translate("MainWindow", "auto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "TCP"))
        self.label_26.setText(_translate("MainWindow", "Source Port"))
        self.label_27.setText(_translate("MainWindow", "Destination Port"))
        self.label_28.setText(_translate("MainWindow", "Length"))
        self.checkBox_20.setText(_translate("MainWindow", "auto"))
        self.label_29.setText(_translate("MainWindow", "Checksum"))
        self.checkBox_21.setText(_translate("MainWindow", "auto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "UDP"))
        self.checkBox_31.setText(_translate("MainWindow", "auto"))
        self.label_43.setText(_translate("MainWindow", "Checksum"))
        self.label_44.setText(_translate("MainWindow", "Type"))
        self.label_45.setText(_translate("MainWindow", "Seq. number"))
        self.label_46.setText(_translate("MainWindow", "Code"))
        self.label_47.setText(_translate("MainWindow", "ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "ICMP"))
        self.groupBox.setTitle(_translate("MainWindow", "Type of Service"))
        self.checkBox.setText(_translate("MainWindow", "Delay"))
        self.checkBox_2.setText(_translate("MainWindow", "Reliability"))
        self.checkBox_3.setText(_translate("MainWindow", "Throughput"))
        self.label_8.setText(_translate("MainWindow", "ECN"))
        self.label_9.setText(_translate("MainWindow", "Precendence"))
        self.label_2.setText(_translate("MainWindow", "Source IP"))
        self.label_3.setText(_translate("MainWindow", "Checksum"))
        self.label_4.setText(_translate("MainWindow", "Total Length"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data"))
        self.checkBox_7.setText(_translate("MainWindow", "auto"))
        self.checkBox_8.setText(_translate("MainWindow", "auto"))
        self.checkBox_9.setText(_translate("MainWindow", "auto"))
        self.label_10.setText(_translate("MainWindow", "Destination IP"))
        self.label_11.setText(_translate("MainWindow", "Protocol"))
        self.label_12.setText(_translate("MainWindow", "Offset"))
        self.label_13.setText(_translate("MainWindow", "IHL"))
        self.label_14.setText(_translate("MainWindow", "ID"))
        self.label_15.setText(_translate("MainWindow", "Version"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Flags"))
        self.checkBox_10.setText(_translate("MainWindow", "Reserved"))
        self.checkBox_11.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_12.setText(_translate("MainWindow", "CheckBox"))
        self.label_16.setText(_translate("MainWindow", "TTL"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "IPv4"))
        self.label.setText(_translate("MainWindow", "Network Adapter"))
        self.checkBox_32.setText(_translate("MainWindow", "auto"))
        self.label_48.setText(_translate("MainWindow", "Source MAC"))
        self.checkBox_33.setText(_translate("MainWindow", "auto"))
        self.label_49.setText(_translate("MainWindow", "Destination MAC"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Packets"))
        self.pushButton.setText(_translate("MainWindow", "Clear"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete"))
        self.pushButton_3.setText(_translate("MainWindow", "Load"))
        self.pushButton_4.setText(_translate("MainWindow", "Add"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Name"))
        self.pushButton_5.setText(_translate("MainWindow", "Save"))
        self.pushButton_6.setText(_translate("MainWindow", "Send all"))
        self.pushButton_7.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
